[build]
  base = "/"
  publish = "public/"

	cache-control = '''
	max-age=0,
	no-cache,
	no-store,
	must-revalidate'''
# An Edge Handler declaration
[[edge_handlers]]
  path = "/*"
  handler = "filterRequests"
