backend:
  name: git-gateway
  #name: github
  branch: master
publish_mode: editorial_workflow
media_folder: packages/landing-gatsby/static/images
public_folder: packages/landing-gatsby/images


collections:
- name: sections
  label: sections
  editor:
    preview: true
  files:
  - name: "navigation"
    label: "navigation menu"
    file: "../../src/data/navigation.yml"
    fields:
    - label: "Navigation items"
      name: "items"
      widget: "list"
      fields:
      - { label: "label", name: "label", widget: "string" }
      - { label: "link",  name: "link",  widget: "string", default: "#" }
      - { label: "order",  name: "order",  widget: "number", default: "9" }

# - label: Pages
#   name: pages
#   editor:
#     preview: true
#   files:
#     - label: Homepage
#       name: homepage
#       file: "pages/index.md"
#       fields:
#   - label: "Site Main page"
#    name: "mainpage"
#    files:
